name: Stock News Scanner

on:
  schedule:
    # Run every 30 minutes during business hours (8 AM - 6 PM EST)
    - cron: '*/30 13-23 * * 1-5'
  workflow_dispatch:  # Allow manual triggering

jobs:
  scan-news:
    runs-on: ubuntu-latest
    permissions:
      issues: write  # Add permission to create issues
      contents: read
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python -c "import nltk; nltk.download('vader_lexicon')"
      - name: Run news scanner
        run: python main.py
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Automatically provided